### ISSUE TITLE
Unable to resolve "react-dom" on 3.3.1

### ISSUE THREAD

**Issue by skyleraustin** [dsuryd/dotnetify-react-native-demo#11]
(re: #7) 

I am still getting this error on 3.3.1

> Unable to resolve module `react-dom` from `\node_modules\dotnetify\dist\dotnetify-react.js`: Module `react-dom` does not exist in the Haste module map or in these directories:
> <redacted>
> 
> This might be related to https://github.com/facebook/react-native/issues/4968
> To resolve try the following:
>   1. Clear watchman watches: `watchman watch-del-all`.
>   2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
>   3. Reset Metro Bundler cache: `rm -rf /tmp/metro-bundler-cache-*` or `npm start -- --reset-cache`.
>   4. Remove haste cache: `rm -rf /tmp/haste-map-react-native-packager-*`.

I have attempted the applicable suggestions

**Comment by dsuryd** [comment]
The import name is changed to dotnetify/react-native.  I’ve updated the
example in the repo.

**Comment by skyleraustin** [comment]
You sure did. Thanks for the quick response!
