### ISSUE TITLE
Error during negotiation request

### ISSUE THREAD

**Issue by malith-gammanpila** [dsuryd/dotnetify-react-native-demo#13]
Got the following error after successful authentication.

`Error during negotiation request.`
![Screenshot_20190503-162404](https://user-images.githubusercontent.com/43638607/57133698-3c579800-6dc1-11e9-8422-3d0a6cd7f666.png)

`Connection Error
Error during negotiation request.` 
![Screenshot_20190503-162513](https://user-images.githubusercontent.com/43638607/57133711-4b3e4a80-6dc1-11e9-8706-23b0f6729111.png)

**Warning**
`This client may be attempting to connect to an incompatible SignalR .Net Core server`.
![Screenshot_20190503-162530](https://user-images.githubusercontent.com/43638607/57133713-4da0a480-6dc1-11e9-9cee-84cd1e292e83.png)

I also found this! https://github.com/dsuryd/dotnetify-react-native-demo/issues/5#issuecomment-440545154

**Is this an outdated example?**
Where can I find an updated [dotnetify](https://github.com/dsuryd/dotNetify) example application for React Native?

**Comment by dsuryd** [comment]
Change the dotnetify.net address to https.
