### ISSUE TITLE
Unable to run on expo

### ISSUE THREAD

**Issue by isaaclem** [dsuryd/dotnetify-react-native-demo#15]
![image](https://user-images.githubusercontent.com/32945572/65563838-84987200-df7d-11e9-9611-7180951d299b.png)

Following the instruction on README.md, supposed `expo start` can kickstart and able to run the app on both simulator, however as seen on the screenshot, I'm having difficulty running the app

**Comment by dsuryd** [comment]
The expo in this repo is several versions behind, and according to your screenshot, it requires at least v.33.  You could try updating it.

**Comment by isaaclem** [comment]
Hi @dsuryd, It is working now, however I'm unable to login. I think it's due to I could start the server on dotnet core part. I will raise another issue for that. Thanks!
