### ISSUE TITLE
Authentication folder missing

### ISSUE THREAD

**Issue by randeeb** [dsuryd/dotnetify-react-native-demo#2]
Not sure if it's intentional, but the auth code depends on files in a /src/Authentication folder, which appears to be missing.

**Comment by dsuryd** [comment]
The auth logic is all in src/Authentication.js, and it’s present.

**Comment by randeeb** [comment]
Oh, I misunderstood the import syntax.  The login button wasn't working, but it worked if I commented out the auth request, and I couldn't find the referenced auth code to dig in.  All set now, thank you.
