### ISSUE TITLE
after installing, it says network request failed, what may be the problem ?

### ISSUE THREAD

**Issue by uskudaristanbul** [dsuryd/dotnetify-react-native-demo#5]
This is really a great project, hope you are continuing to develop this,

the problem is : 
After dotnet build and dotnet run command, when I enter guest and dotnetify credentials,  log in screens is saying Network request failed.

**Comment by dsuryd** [comment]
Sounds like it couldn't make connection to the local server.   Check your logs, what particular network call it's trying to make and what's the failure code?  Also, could it be this issue: https://github.com/dsuryd/dotNetify/issues/114.

**Comment by uskudaristanbul** [comment]
Hi,
after cloning repository and creating react native app, do I must change something in codes such as server url ip or something else ?

because server url is pointing another ip that I dont know. 

In App.js file :
const androidEmulatorServerUrl = "http://169.254.80.80:5000";
const liveServerUrl = "http://dotnetify.net";
