### ISSUE TITLE
Unable to resolve "react-dom" on 3.2.0

### ISSUE THREAD

**Issue by skyleraustin** [dsuryd/dotnetify-react-native-demo#7]
I get the following error when using 3.2.0. Reverting to 3.0.1 resolves the error.

Unable to resolve "react-dom" from "node_modules\dotnetify\dist\dotnetify-react.js"

**Comment by skyleraustin** [comment]
@dsuryd Any thoughts on this? I am stumped. I would like to make sure I am on latest before logging any more issues.

**Comment by dsuryd** [comment]
This will be addressed in next version update, tomorrow at the earliest.

**Comment by dsuryd** [comment]
New version 3.3.1 has been published.
