### ISSUE TITLE
Top-level connection handling

### ISSUE THREAD

**Issue by skyleraustin** [dsuryd/dotnetify-react-native-demo#8]
It seems that neither dotnetify.connectionStateHandler or exceptionHandler on dotnetify.react.connect are capable of handling top-level connection issues. Backend server communication issues (say, server not listening) result in red screens in Expo, and presumably app crashes in production mode.

It looks like your demo app does not have this issue on 2.0.8 (a failed connection seems to hang with no feedback, but also no crashes), but upgrading it to 3.0.1 reproduces what I am seeing.

**Comment by skyleraustin** [comment]
Great. Thank you for being so responsive.

**Comment by dsuryd** [comment]
New version 3.3.1 has been published.
