### ISSUE TITLE
Library potentially needs updates.

### ISSUE THREAD

**Issue by hdusten** [dsuryd/dotnetify-react-native-demo#9]
Hey Dsuryd,

Trying to run and test this this repository and we are working up to login which then fails dramatically with the following errors:

Client output:
11:24:13 AM: This client may be attempting to connect to an incompatible SignalR .NET Core server.
- node_modules\react-native\Libraries\ReactNative\YellowBox.js:82:15 in warn
- node_modules\dotnetify\dist\dotnetify-hub.js:329:37 in <unknown>
- node_modules\jquery-deferred\lib\jquery-callbacks.js:87:6 in fire
- node_modules\jquery-deferred\lib\jquery-callbacks.js:200:11 in fireWith
* null:null in fire
- node_modules\dotnetify\dist\signalR-netfx.js:703:33 in onFailed
- node_modules\dotnetify\dist\signalR-netfx.js:737:21 in success
- ... 10 more stack frames from framework internals
11:24:13 AM: SignalR: reconnecting
11:24:13 AM: SignalR: connecting
11:24:13 AM: SignalR: connecting
11:24:13 AM: SignalR: reconnecting
11:24:13 AM: SignalR: Error during negotiation request.
11:24:13 AM: SignalR: disconnected
11:24:13 AM: SignalR: disconnected
11:24:14 AM: Stopping packager...
11:24:14 AM: Packager stopped.

Server Output: 
      Request starting HTTP/1.1 GET http://192.168.1.16:5000/signalr/negotiate?clientProtocol=1.5&connectionData=%5B%7B%22name%22%3A%22dotnetifyhub%22%7D%5D application/json; charset=UTF-8
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 0.0984ms 200

Thanks

**Comment by dsuryd** [comment]
Yes, both the library and the react native example need update.  It's in the works.

**Comment by dsuryd** [comment]
Try v3.3.1.
